# file: postgresql/tasks/users_privileges.yml

- name: PostgreSQL | Update the user privileges
  postgresql_privs:
    database: "{{item[0].name}}"
    state: present
    type: "{{item[1].type | default(omit)}}"
    objs: "{{item[1].objs | default(omit)}}"
    schema: "{{item[1].schema | default(omit)}}"
    roles: "{{item[1].name}}"
    privs: "{{item[1].privs}}"
    port: "{{postgresql_port}}"
    login_host: "{{item.host | default(omit)}}"
    login_user: "{{postgresql_admin_user}}"
  with_nested:
    - "{{ postgresql_databases }}"
    - "{{ postgresql_user_privileges }}"
